### ISSUE TITLE
Ruptura de caracteres especiales.

### ISSUE THREAD

**Issue by jpilorget** [pdelboca/georefar#1]
Buenas! Hay un problema en cómo levanta los caracteres especiales el rawToChar() -se ve en los ejemplos de uso-, ya lo arreglé en calles.R. Te hago un pull request y si te copa agregalo.
Saludos y felicitaciones por la iniciativa!

**Comment by pdelboca** [comment]
Genial, ya hice el merge. Pensé que era un problema con el encoding de Windows, tenia pensado resolverlo. Cuando agregas los paquetes en la doc de roxygen2, los metodos van separados por espacio y no por comas, lo resolvi despues con un commit.

Se resuelve en el pull request #2 y commit  91bf487317fb7dad7ce938de38d70496ef85445f

**Comment by jpilorget** [comment]
Mala mía lo de los métodos, asumí que era como en Python y no probé esa parte del código, gracias!
